config/routes.rb
Rails.application.routes.draw do

  match '',           to:'top_page#index',     via:'get',  as:'root'
  match '/attending', to:'top_page#attending', via:'post', as:'attending'
  match '/leaving',   to:'top_page#leaving',   via:'poat', as:'leaving'

  scope :history do
    match '',           to:'attending_hist#index',  via:'get',  as:'attending_hist_index'
    match 'edit/:id',   to:'attending_hist#edit',   via:'get',  as:'attending_hist_edit'
    match 'update/:id', to:'attending_hist#update', via:'post', as:'attending_hist_update'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController

  def index
  end

  def attending
    @attending_time = AttendingTime.new(attending_params)
    if @attending_time.save
      redirect_to root_path
    else
      render :index, alert: '保存できませんでした'
    end
  end

  def leaving
  end

  private

  def attending_params
    {
      year:    params[:year],
      month:   params[:month],
      day:     params[:day],
      hour:    params[:hour],
      minute:  params[:minute]
    }
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workrecord</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>
    <div class="header"></div>
    <div class="col-md-12 col-sm-12 col-xs-12 user_icon">
      <i class="fa fa-user-circle-o fa-4x pull-left"></i>
    </div>
    <%= yield %>
  </body>
</html>

app/views/top_page/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 col-sm-2 col-xs-2"></div>
    <div class="col-md-8 col-sm-8 col-xs-8 hello_user text-center">
      <h1>Work Record</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
      <%= form_tag attending_path, method: :post do %>
      <input type="hidden" name="minute" value="<%=  %>">
      <button type='submit' name='attending' value='*' class="btn btn-lg btn-default menu_button">出勤</button>
      <% end %>
    </div>

    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
      <%= link_to '退勤',     {:controller => :top_page, :action => :leaving}, :class => 'btn btn-info menu_button' %>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
      <%= link_to '出勤履歴', {:controller => :top_page, :action => :attending}, :class => 'btn btn-info menu_button' %>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
      <%= link_to '給料計算', {:controller => :top_page, :action => :attending}, :class => 'btn btn-info menu_button' %>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
      <%= link_to '時給設定', {:controller => :top_page, :action => :attending}, :class => 'btn btn-info menu_button' %>
    </div>
  </div>
</div>